-- =====================================================
-- SAFE RECOVERY SCRIPT - READ ONLY STRUCTURE CHANGES
-- This script ONLY adds new columns/tables and inserts data
-- It does NOT modify, delete, or alter any existing columns
-- =====================================================

-- 1. ADD new column 'usage_count' to fast_coupons (if not exists)
ALTER TABLE fast_coupons ADD COLUMN IF NOT EXISTS usage_count INTEGER DEFAULT 0;

-- 2. CREATE new table for tracking (if not exists) - does not touch existing table
CREATE TABLE IF NOT EXISTS fast_coupon_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ADD new columns to 'fast_coupon_usage' (only if they don't exist)
-- These commands are NO-OP if columns already exist
ALTER TABLE fast_coupon_usage ADD COLUMN IF NOT EXISTS client_phone TEXT;
ALTER TABLE fast_coupon_usage ADD COLUMN IF NOT EXISTS coupon_code TEXT;
ALTER TABLE fast_coupon_usage ADD COLUMN IF NOT EXISTS order_id BIGINT;
ALTER TABLE fast_coupon_usage ADD COLUMN IF NOT EXISTS discount_amount NUMERIC DEFAULT 0;
ALTER TABLE fast_coupon_usage ADD COLUMN IF NOT EXISTS used_at TIMESTAMPTZ DEFAULT NOW();

-- 4. UPDATE usage counts in fast_coupons based on order history
-- This only updates the NEW 'usage_count' column we just added
WITH coupon_counts AS (
    SELECT 
        UPPER(TRIM(coupon_code)) as code, 
        COUNT(*) as usage_count
    FROM fast_orders 
    WHERE coupon_code IS NOT NULL 
    AND coupon_code != ''
    GROUP BY UPPER(TRIM(coupon_code))
)
UPDATE fast_coupons c
SET usage_count = COALESCE(cc.usage_count, 0)
FROM coupon_counts cc
WHERE UPPER(TRIM(c.code)) = cc.code;

-- 5. INSERT historical data (only new records)
-- Uses ON CONFLICT to safely skip duplicates without error
INSERT INTO fast_coupon_usage (phone, client_phone, coupon_code, order_id, discount_amount, used_at)
SELECT 
    o.client_phone,
    o.client_phone,
    UPPER(TRIM(o.coupon_code)),
    o.id,
    COALESCE(o.coupon_discount, 0),
    o.created_at
FROM fast_orders o
WHERE o.coupon_code IS NOT NULL 
AND o.coupon_code != ''
AND o.client_phone IS NOT NULL
ON CONFLICT DO NOTHING;

-- =====================================================
-- SUMMARY OF ACTIONS:
-- ✅ Adds new columns (does not touch existing ones)
-- ✅ Creates tables if missing (does not alter existing)
-- ✅ Inserts new records (does not modify existing data)
-- ❌ Does NOT delete anything
-- ❌ Does NOT modify existing constraints
-- ❌ Does NOT alter existing column types or properties
-- =====================================================
