-- Create table for special discounts configuration
create table if not exists public.fast_special_discounts (
    id bigint generated by default as identity primary key,
    store_id bigint default 1,
    min_orders integer not null default 10,
    discount_type text not null check (discount_type in ('percentage', 'fixed')),
    discount_value numeric(10,2) not null,
    min_order_value numeric(10,2) default 0,
    active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now()),
    unique(store_id)
);

-- Enable RLS
alter table public.fast_special_discounts enable row level security;

-- Policies
create policy "Public read access"
    on public.fast_special_discounts for select
    using (true);

create policy "Admin full access"
    on public.fast_special_discounts for all
    using (true)
    with check (true);

-- Insert default configuration
insert into public.fast_special_discounts (store_id, min_orders, discount_type, discount_value, min_order_value)
values (1, 10, 'percentage', 10.00, 0)
on conflict (store_id) do nothing;
